## as yaml are case sensitive make sure things are writen specifically
---
apiVersion: kind.x-k8s.io/v1alpha4       # added document start to satisfy yamllint
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
    extraPortMappings:                  # corrected key name and kept 4-space indent
      - containerPort: 80               # indented 6 spaces under “extraPortMappings:”
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
